CSS/Controllers/SPMapSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.ViewModels;
using BLL.Models;
using BLL;
using Newtonsoft.Json;
using System.IO;
namespace CSS.Controllers
{
    [Authorize]
    public class SPMapSearchController : Controller
    {
        ChoiceSolutionsEntities css = new ChoiceSolutionsEntities();
        public IEnumerable<ServiceOfferingsNew> ServiceOfferings { get; set; }

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Search(string sptype)
        {
          //  SPMapSearchViewModel search = new SPMapSearchViewModel();
         //   search = LoadSASearch(search, "", 0);
            //search = LoadSPSearch(search, "", 0);
        //    search.Distance = 20;

            //LoadSPPager(search, null, "1", "1");

            //for Create Auto Assignment
            Session["SPTYPE"] = "";
            if(sptype == "fav")
            {
                Session["SPTYPE"] = "fav";
            }
            else if(sptype == "act")
            {
                Session["SPTYPE"] = "act";
            }
                //AutoAssignmentViewModel viewModel;
                        
                //viewModel = new AutoAssignmentViewModel();
                //viewModel.UseMasterPageLayout = true;
                //viewModel.claim.IsSingleDeductible = false;//Default to SingeDeductible
                CSS.Models.User loggedInUser = CSS.AuthenticationUtility.GetUser();
              //  BLL.User LoggedInUser = css.Users.Find(loggedInUser.UserId);            
            //

                return View(loggedInUser);
        }
       public string isSessionValid(object value)
       {
           if (value==null)
           {
               return "";
           }
           string sessionValue ="";
           if (!string.IsNullOrEmpty(Session["SPTYPE"].ToString()))
           {
               sessionValue = Session["SPTYPE"].ToString();
           }
           return sessionValue;
       }
        public JsonResult InitSPMapSearch()
        {
            SPMapSearchNewViewModel search = new SPMapSearchNewViewModel();
             search.Distance = 100;


             if (isSessionValid(Session["SPTYPE"]) == "fav" || isSessionValid(Session["SPTYPE"]) == "act")
             {
                
               search = LoadSPSearch(search, ",0", search.Distance,0);//INPSW-32
             }

             return Json(search, JsonRequestBehavior.AllowGet);
        }

        public SPMapSearchViewModel LoadSASearch(SPMapSearchViewModel search, string Location, int distance)
        {
            if (search.CatCode != null && search.CatCode.Trim() == "0") search.CatCode = null;
            //if (search.SeverityLevel == 0) search.SeverityLevel = null;
            //if (search.LossType == 0) search.LossType = null;
            //if (search.InsuranceCompany == 0) search.InsuranceCompany = null;
            //SPMapSearchViewModel search = new SPMapSearchViewModel();

            if (Location == ",0") Location = "";
            search.ClaimList = css.usp_SearchDispatchClaimsGetList(Location, distance, search.CatCode, search.SeverityLevel, search.LossType, search.InsuranceCompany).ToList();
            var Filteredzip = (from a in search.ClaimList
                               select new { a.PropertyZip, a.Lat, a.Lng }
                        ).Distinct().ToList();
            search.spfilteredZip = new List<SAfilteredZip>();
            foreach (var z in Filteredzip)
            {
                SAfilteredZip FilteredZp = new SAfilteredZip();
                FilteredZp.Zip = z.PropertyZip.ToString();
                FilteredZp.Latitude = z.Lat.ToString();
                FilteredZp.Lontitude = z.Lng.ToString();
                FilteredZp.SPAssignments = new List<SMAssignments>();
                List<usp_SearchDispatchClaimsGetList_Result> clForZip = search.ClaimList.Where(a => a.PropertyZip == z.PropertyZip.ToString()).ToList();
                foreach (usp_SearchDispatchClaimsGetList_Result c in clForZip)
                {
                    SMAssignments sma = new SMAssignments();
                    Claim cl = new Claim();
                    cl.ClaimNumber = c.ClaimNumber;
                    cl.ClaimId = c.ClaimId;
                    cl.ClaimNumber = c.ClaimNumber;
                    cl.PolicyNumber = c.PolicyNumber;
                    cl.InsuredFirstName = c.InsuredFirstName;
                    cl.InsuredLastName = c.InsuredLastName;
                    cl.PropertyCity = c.PropertyCity;
                    cl.PropertyZip = c.PropertyZip;
                    cl.SeverityLevel = c.SeverityLevel;
                    cl.ClaimCreatedDate = c.AssignmentDate; //shoud be claim created date
                    cl.LOBId = c.LOBId;
                    cl.ClientPointOfContactUserId = c.ClientPointOfContactUserId;
                    //Add
                    Company comp = new Company();
                    comp.CompanyName = c.CompanyName;
                    comp.CompanyId = c.CompanyId; //new change
                    cl.Company = comp;
                    sma.CauseType = c.LossType;
                    sma.AssignmentId = c.AssignmentId;
                    sma.AssignmentDate = c.AssignmentDate.ToShortDateString();
                    //cl.FileStatus = c.FileStatus;    
                    sma.ClaimDetail = cl;
                    FilteredZp.SPAssignments.Add(sma);
                }
                search.spfilteredZip.Add(FilteredZp);
            }
            if (Session["ZipList"] != null)
            {
                Session["ZipList"] = search.spfilteredZip;
            }
            else
            {
                Session.Add("ZipList", search.spfilteredZip);
            }

            return search;
        }

        public SPMapSearchNewViewModel LoadSPSearch(SPMapSearchNewViewModel search, string Location, int distance,Int64 Autoassignmentid)//INPSW-32
        {
            if (Location == ",0")
            {
                Location = "";
            }
            search.IsLoggedIN = true;
            CSS.Models.User loggedInUser = CSS.AuthenticationUtility.GetUser();
            search.SPMapSearchtype = SPMapSearchType.MainSearch;
            if (isSessionValid(Session["SPTYPE"]) == "fav")
            {
                search.SPMapSearchtype = SPMapSearchType.Fevorite;
                search.Splist = css.AutoSearchDispatchSPGetList(Location, distance, search.Rank, search.SPName, search.ServiceType, loggedInUser.UserId, 1, 0, search.SPActiveStatus, Autoassignmentid).ToList();//INPSW-32
                search.IsActiveSP = true;
            }
            else if (isSessionValid(Session["SPTYPE"]) == "act")
            {
                search.SPMapSearchtype = SPMapSearchType.ActiveLoc;
                search.Splist = css.AutoSearchDispatchSPGetList(Location, distance, search.Rank, search.SPName, search.ServiceType, loggedInUser.UserId, 0, loggedInUser.HeadCompanyId, search.SPActiveStatus, Autoassignmentid).ToList(); //INPSW-32
                search.IsActiveSP = false;
            }
            else
            {
                search.Splist = css.AutoSearchDispatchSPGetList(Location, distance, search.Rank, search.SPName, search.ServiceType, loggedInUser.UserId, 0, 0, search.SPActiveStatus, Autoassignmentid).ToList();//INPSW-32
                search.IsActiveSP = true;
            }
            foreach (AutoSearchDispatchSPGetList_Result s in search.Splist)
            {
                s.imagePath = Utility.GetClaimServiceProviderAbsoluteDocPath((Int32)s.HeadCompanyID, s.imagePath);
            }
           
          //Commented for IADA 
            //changes for unqualified service provider
            //if (search.InsuranceCompany != 0)
            //{
            //    List<usp_AutoSearchDispatchSPGetList_Result> tempSP = new List<usp_AutoSearchDispatchSPGetList_Result>();
            //    foreach (usp_AutoSearchDispatchSPGetList_Result s in search.Splist)
            //    {
            //        if (css.UnQualifiedServiceProviders.Where(x => x.SPId == s.UserId && x.CompanyId == search.InsuranceCompany && x.LOBId==null && x.ClientPOCId==null).ToList().Count() == 0)
            //        {
            //            tempSP.Add(s);
            //        }
            //    }
            //    search.Splist = tempSP;
            //}

            //search.SPServiceproviders = new List<BLL.User>();
            ////List<usp_SearchDispatchSPGetList_Result> spForZip = search.Splist.Where(a => a.Zip == z.PropertyZip.ToString()).ToList();
            //foreach (usp_AutoSearchDispatchSPGetList_Result s in search.Splist)
            //{
            //    User u = new BLL.User();
            //    u.City = s.City;
            //    u.FirstName = s.Firstname;
            //    u.LastName = s.LastName;
            //    u.StreetAddress = s.StreetAddress;
            //    u.City = s.City;
            //    u.State = s.State;
            //    u.Zip = s.Zip;
            //    u.Email = s.Email;
            //    u.HomePhone = s.HomePhone;
            //    u.WorkPhone = s.WorkPhone;
            //    u.MobilePhone = s.MobilePhone;
            //    u.UserId = Convert.ToInt64(s.UserId);
            //    ServiceProviderDetail spd = new ServiceProviderDetail();
            //    spd.TypeOfClaimsPref = s.TypeOfClaimsPref;
            //    u.ServiceProviderDetail = spd;
            //    search.SPServiceproviders.Add(u);
            //}
            //if (Session["SPList"] != null)
            //{
            //    Session["SPList"] = search.SPServiceproviders;
            //}
            //else
            //{
            //    Session.Add("SPList", search.SPServiceproviders);
            //}
            return search;
        }

        public SPMapSearchViewModel LoadSessionSAData(SPMapSearchViewModel search)
        {
            search.spfilteredZip = new List<SAfilteredZip>();

CSS/Views/Shared/_AssignmentDetailsReservesBasedonCoverageId.cshtml
@model BLL.ViewModels.XACTClaimsInfoViewModel
<table cellpadding="3" cellspacing="0" width="100%">
                                <thead class="tableHeader">
                                    <tr valign="top">

                                        <td widht="10%">Revised  Date
                                        </td>
                                        <td width="15%" align="right">Revised Change
                                        </td>
                                        <td width="75%"></td>

                                    </tr>
                                </thead>
                                @{
                                    int j = 0;
                                    //BLL.ChoiceSolutionsEntities css = new BLL.ChoiceSolutionsEntities();
                                    //Model.ClaimCoveragesBasedonClaimid = css.ClaimCoveragesBasedonClaimIdGetList(Model.claim.ClaimId).ToList();
                                    //Model.ReserveListBasedonCoverageid = null;
                                    //foreach (var coverage in Model.ClaimCoveragesBasedonClaimid)
                                    //{
                                    //    Model.ReserveListBasedonCoverageid = css.ClaimReservesBasedonCoverageIdGetList(coverage.ClaimCoverageId).ToList();
                                    //    foreach (var p in css.ClaimReservesBasedonCoverageIdGetList(reserve.ClaimCoverageId))
                                    //    {
                                    //        viewModel.ReserveListBasedonCoverageid.Add(p.ClaimCoverageId);
                                    //    }
                                           foreach (var reserve in Model.ReserveListBasedonCoverageid)
                                         {
                                    
        
                                    <tr class="@(j % 2 == 0 ? "tableRowAlternate" : "tableRow")">
                                        <td>
                                            @reserve.ReserveAddedDate.ToString("MM/dd/yyyy")
                                        </td>
                                        <td align="right">
                                           @reserve.ReserveAmount.ToString("$0.00")
                                        </td>
                                        <td></td>
                                      
                                    </tr>
                                        j++;
                            }
                                    }
                            @*int j = 0;
                            
                            //if (Model.coverage.ClaimCoverageId != null)
                            //{
                                //Model.ReserveListBasedonCoverageid = css.ClaimReservesBasedonCoverageIdGetList(Model.coverage.ClaimCoverageId).Tolist();*@
                             
                                
                           @* }*@
                                
                            </table>

CSS/Views/Shared/_DiarySummaryOverdueClaimsList.cshtml
@model BLL.ViewModels.DiarySummaryOverDueClaimsListViewModel
@using CSS

@*<div style="text-align:left;">
        <table>
            @if (!String.IsNullOrEmpty(Model.Level1_Desc))
            {
                <tr><td>@Model.Level1Group_Desc:</td><td width="10px;"></td><td><b>@Model.Level1_Desc</b></td></tr>
            }
            @if (!String.IsNullOrEmpty(Model.Level2_Desc))
            {
                <tr><td>@Model.Level2Group_Desc:</td><td width="10px;"></td><td><b>@Model.Level2_Desc</b></td></tr>
            }
            @if (!String.IsNullOrEmpty(Model.Level3_Desc))
            {
                <tr><td>@Model.Level3Group_Desc:</td><td width="10px;"></td><td><b>@Model.Level3_Desc</b></td></tr>
            }
        </table>


        <br />
    </div>*@

<div style="text-align:left;">
    <table>
        <tr><td>Company:</td><td width="10px;"></td><td><b>@Model.CompanyName</b></td></tr>
        @if (Model.CSSPOCUserId > 0 && !String.IsNullOrEmpty(Model.CSSPOCName))
        {
            <tr><td>CSS POC:</td><td width="10px;"></td><td><b>@Model.CSSPOCName</b></td></tr>
        }
        @if (Model.SPUserId > 0 && !String.IsNullOrEmpty(Model.SPName))
        {
            <tr><td>SP:</td><td width="10px;"></td><td><b>@Model.SPName</b></td></tr>
        }
    </table>

    <br />
</div>

<div>
    <table class="col-md-12">
        <thead style="background-color: #406E98 !important; color:white; height:25px;">
            <tr style="height: 30px;">
                <td width="">Claim #</td>
                <td width="">Insured</td>
                <td width="">Due Date</td>
                <td width="" style="text-align:center;">Overdue Diaries</td>
                @* <td width="40%">Claim #</td>
                    <td width="60%">Overdue Diary Count</td>*@
            </tr>
        </thead>

        @{
            int i = 0;
            foreach (var claim in Model.ClaimsList)
            {
                <tr class="@(i%2==0?"tableRowAlternate":"tableRow")">
                    <td style="text-align:left;">@Html.ActionLink(claim.ClaimNumber, "Details", "AutoAssignment", new { @claimId = Cypher.EncryptString(claim.ClaimId.ToString()) }, null)</td>
                    <td>@claim.InsuredName</td>

                    <td>
                        @if (claim.DueDate.HasValue)
                        {
                            @(claim.DueDate.Value.Month + "/" + claim.DueDate.Value.Day + "/" + claim.DueDate.Value.Year);
                        }
                    </td>
                    <td>@claim.OverDueDiaryCount</td>
                </tr>
                        i++;
            }
            if (i == 0)
            {
                <tr class="tableRowAlternate"><td colspan="4" style="text-align:center;">No Overdue Claims</td></tr>
            }
        }
    </table>
</div>




@*<div style="text-align:left;">
        Company: @Model.CompanyName<br />
        @if (Model.CSSPOCUserId > 0 && !String.IsNullOrEmpty(Model.CSSPOCName))
        {
            @:CSS POC: @Model.CSSPOCName<br />
    }
        @if (Model.SPUserId > 0 && !String.IsNullOrEmpty(Model.SPName))
        {
            @:SP: @Model.SPName<br />
    }<br />
    </div>*@
@*<table width="100%">
        <thead class="tableHeader">
            <tr>

                <td width="35%">Claim #</td>
                <td width="25%">Insured</td>
                <td width="30%">Due Date</td>
                <td width="10%">Overdue Diaries</td>
            </tr>
        </thead>
        @{
            int i = 0;
            foreach (var claim in Model.ClaimsList)
            {
                <tr class="@(i%2==0?"tableRowAlternate":"tableRow")">
                    <td style="text-align:left;">@Html.ActionLink(claim.ClaimNumber, "Details", "PropertyAssignment", new { @claimId = Cypher.EncryptString(claim.ClaimId.ToString()) }, null)</td>
                    <td>@claim.InsuredName</td>

                    <td>
                        @if (claim.DueDate.HasValue)
                        {
                            @(claim.DueDate.Value.Month + "/" + claim.DueDate.Value.Day + "/" + claim.DueDate.Value.Year);
                        }
                    </td>
                    <td>@claim.OverDueDiaryCount</td>
                </tr>
                        i++;
            }
            if (i == 0)
            {
                <tr class="tableRowAlternate"><td colspan="4" style="text-align:center;">No Overdue Claims</td></tr>
            }
        }
    </table>*@

CSS/Views/Shared/_ItemList.cshtml
 @Ajax.ActionLink("Refresh", "RefreshItems", new AjaxOptions() {
     UpdateTargetId = "ItemList",
     HttpMethod = "Post"})

CSS/Views/Shared/_NotificationList.cshtml
@using BLL
@model IEnumerable<NotificationList_Result>
@{
    ChoiceSolutionsEntities css = new ChoiceSolutionsEntities();               
}


<div id="divNotification" class="modal fade" tabindex="-1" data-width="400">
    <div class="modal-dialog" style="width:800px;">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #406E98; color: white;">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Notification</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="table-scrollable col-md-12">
                        <table class="table table-hover ">
                            <thead style="background-color: #406E98 !important; color: white;">
                                <tr>
                                    <th> Date </th>
                                    <th> Subject </th>
                                    <th> Comment </th>
                                    <th> Source </th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    if (Model.ToList().Count() > 0 && Model != null)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>@item.DateCreated</td>
                                                <td>
                                                    <a onclick="ShowNotification(@item.AutoNoteID);">@item.Subject</a>
                                                </td>
                                                <td>@item.Comment</td>
                                                @{
                                            var userdetails = css.Users.Where(x => x.UserId == item.ToUserId).FirstOrDefault();
                                            var company = css.Companies.Where(x => x.CompanyId == userdetails.HeadCompanyId).FirstOrDefault();
                                                }
                                                <td>@company.CompanyName</td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn dark btn-outline">Close</button>                
            </div>
        </div>
    </div>
</div>

CSS/Views/Shared/_NuGenAssignmentSearchFilter.cshtml
@model BLL.ViewModels.NuGenAutoAssignmentSearchViewModel
@{
    CSS.Models.User loggedInUser = CSS.AuthenticationUtility.GetUser();
    BLL.ChoiceSolutionsEntities css = new BLL.ChoiceSolutionsEntities();

}

@{
    ViewBag.Title = "_NuGenAssignmentSearchFilter";
}
<style>
    .fontsizefortbl {
        font-size: 13px !important;
    }

        .fontsizefortbl input, select {
            height: 28px !important;
            padding: 0px !important;
        }

    .form-group {
        margin-bottom: 12px !important;
    }

    .input-medium {
        width: 100% !important;
    }


    .portlet.box > .portlet-title > .tools > a.expand {
        background-image: url(../img/portlet-expand-icon-white.png);
    }

    .portlet.box > .portlet-title > .tools > a.collapse {
        background-image: url(../img/portlet-collapse-icon-white.png);
    }
</style>

<script type="text/javascript">

    function keypressHandler(e) {
        if (e.which == 13) {
            e.preventDefault(); 
            $('#SubmitButton').val = null;
            $("#formNugenInvoicesSearch").submit();
        }
    }
    $('#formNugenInvoicesSearch').keypress(keypressHandler);

</script>




@{string divSearch = "";

divSearch = "style=display:none;";
string Expand = "expand";
}

<div class="portlet box blue fontsizefortbl" id="frmNuGensearchfilter" style="margin-bottom: 0px;">
    <div class="portlet-title col-md-12" style="background-color:#406E98 !important">
        <div class="caption col-md-10">
            <div class="form-group">
                <div class="col-md-2">
                    <span class="caption-subject font-white-hoki bold uppercase" style="font-size:16px; ">Quick Search</span>
                </div>
                <div class="col-md-9" style="font-size:13px;">
                    <div class="col-md-6 ">
                        <label class="col-md-5 control-label" style="margin-left: -15px;">Claim Name:</label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.objXactAutoAssignmentSearchViewModel.InsureName, new { id = "objXactAutoAssignmentSearchViewModel.txtInsuredname", @class = "form-control", @style = "margin-left: -20px;" })
                        </div>
                    </div>
                    <div class="col-md-6 ">
                        <label class="col-md-5 control-label" style="margin-left: -15px;">Claim Number:</label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.objXactAutoAssignmentSearchViewModel.AutoClaimNumber, new { id = "objXactAutoAssignmentSearchViewModel.txtClaimnumber", @class = "form-control", @style = "margin-left: -20px;" })
                        </div>
                    </div>
                </div>
                <div class="col-md-1 " style=" margin-left: -40px;">
                    <button type="button" class="btn green-meadow" onclick="GetSearchList();">Search</button>
                </div>
            </div>
        </div>
        <div class="col-md-2 tools">
            <a style="text-decoration:underline; font-size:11px; color:white;white-space:nowrap;" href="javascript:;" class="@Expand">Advanced</a>
        </div>
    </div>
    <div class="portlet-body" @divSearch>
        <div class="form-horizontal" role="form">
            @Html.Partial("_NuGenClaimFilter", Model)
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="button" class="btn blue" onclick="GetSearchList();">Search</button>
                </div>
            </div>
        </div>
    </div>
</div>

CSS/Views/Shared/_QuickSearch.cshtml
@using CSS
@using BLL
@*@model BLL.ViewModels.XactAutoAssignmentSearchViewModel*@
@{
    CSS.Models.User loggedInUser = CSS.AuthenticationUtility.GetUser();
}


<style type="text/css">
    .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {
        position: relative;
        min-height: 1px;
        padding-left: 0px !important;
        /* padding-left: 15px; */
        padding-right: 15px;
    }
</style>
<div class="row" style="margin-top: -15px; margin-left: -10px;">
    <div class="col-md-12" style="background-color:#EDF7FB; border: 1px solid lightgray; border-radius:5px !important;">
        @*<div class="col-md-3 " style="margin-top:5px;">
            <div class="col-md-5" style="text-align:center;">
                <label class="form-control-static"> <b> Quick Search:</b></label>
                <a style="text-decoration:underline; font-size:11px;" href="javascript:toggle();">Advanced</a>
            </div>
            <div style="padding-left: 5px;" class="col-md-4">
                <input type="text" class="form-control " style="width:85px; height:28px;margin:3px 0px; font-size: 12px;" placeholder="Name">
                <input type="text" class="form-control " style="width:85px; height:28px;margin:3px 0px; font-size: 12px;" placeholder="Claim #">
            </div>
            <div style="padding-left: 5px;" class="col-md-3">
                <button class="btn default btnradious" style="height:55px; border-color:darkgray; font-weight:bold;">Refresh</button>
            </div>
        </div>*@
        <div class="col-md-9" style="text-align:left; margin-top:5px; margin-bottom: 5px;">
            @{
                if(loggedInUser.UserTypeId==2)
                {
                    
               
            <button class="btn yellow  btnradious btncolor" style="height:60px; width:155px; margin-left:5px; font-weight:bold;" onclick="location.href = '@Url.Action("AutoAssignment", "AutoAssignment")'">Create Assignment</button>
            <button class="btn yellow  btnradious btncolor" style="height:60px; width:155px; margin-left:5px; font-weight:bold;" onclick="Redirecting()">Dispatch<br />Service Provider</button>
            <button class="btn yellow  btnradious btncolor" style="height:60px; width:155px; margin-left:5px; font-weight:bold;">Import Claims</button>
            <button class="btn yellow  btnradious btncolor" style="height:60px; width:155px; margin-left:5px; font-weight:bold;">Batch Payments</button>
            @*<button class="btn default  btnradious" style="height:55px; width:155px; margin-left:5px; border-color:darkgray; font-weight:bold;" onclick="btnAssignInternalContact_Click();">Assign<br />Internal Contact</button>*@
                }
}
            @*<input type="button" onclick="location.href = 'AutoAssignment';" class="btn yellow  btnradious btncolor" value="Create Assignment" style="height:60px; width:155px; margin-left:5px;">
                <input type="button" class="btn yellow  btnradious btncolor" value="Dispatch&#13;Service Provider" style="height:60px; margin-left:5px; width:151px;">
                <input type="button" class="btn yellow  btnradious btncolor" value="Import Claims" style="height:60px; margin-left:5px; width:151px;">
                <input type="button" class="btn yellow  btnradious btncolor" value="Batch Payments" style="height:60px; margin-left:5px; width:151px;">
                <input type="button" class="btn default btnradious " value="Assign CSS POC" style="height:60px; margin-left:5px; width:130px;">*@

        </div>        
    </div>
</div>
<script>
    @*function Redirecting() {

        ClearCookie();
        sessionStorage.setItem('Linkidname', 'liSearchAssign');

        location.href = '@Url.Action("Search", "SPMapSearch")'
    }*@
</script>

CSS/Views/Shared/_ReportViewer.cshtml
@model BLL.ViewModels.ReportViewer
<style>
    .palet {
        background-color: #222222;
        padding: 10px;
        -webkit-border-radius: 12px;
        -moz-border-radius: 12px;
        -ms-border-radius: 12px;
        -o-border-radius: 12px;
        border-radius: 12px;
        border: 2px solid #222222;
    }

    #reportViewer .portlet-body {
        background-color: white;
    }
     .holds-the-iframe {
        background: url(/Content/Images/waiting1.gif) center center no-repeat;
    }
</style>
@if (!String.IsNullOrEmpty(Model.ReportURL))
{
    <div class="palet" id="reportViewer">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box blue-hoki">
                    <div class="portlet-title" style="background-color:#406E98 !important">
                        <div class="caption">
                            <i class="fa fa-gift"></i>@Model.ReportTitle
                        </div>
                        <div class="tools">
                            @if (Model.BackButtonDisplay)
                            {
                                <button type="button" id="btnCancel" onclick="javascript:BackBt_Click();" class="btn btn-Default" style="margin-bottom: 0px;color:blue">Filter</button>
                            }
                        </div>
                    </div>
                    <div id="rptViewerBody" class="portlet-body holds-the-iframe">

                        <iframe src="@Url.Content(Model.ReportURL)" onload="onReportViewerLoad(this)" frameborder="0" width="100%" height="1050px"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script>
    function onReportViewerLoad()
    {
        $('#rptViewerBody').removeClass("holds-the-iframe");
    }
</script>