CSS/Controllers/ServiceProviderRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using BLL.Models;
using BLL.ViewModels;
using System.Data.Objects;
using System.Data;
using System.IO;
using System.Configuration;

using System.Drawing;
using System.IO;
using System.Web.UI;
using System.Threading.Tasks;
using System.Text.RegularExpressions;
using System.Drawing.Imaging;
namespace CSS.Controllers
{
    [System.Web.Mvc.Authorize]
    public class ServiceProviderRegistrationController : Controller
    {

        #region Basic Functionality

        #region Objects & Variables

        ChoiceSolutionsEntities css = new ChoiceSolutionsEntities();
      //  ClaimType claimtype = new ClaimType();
      //  User objUser = new User();
      //  ServiceProviderDetail objServiceProviderDetails = new ServiceProviderDetail();
     
        #endregion
      
        #region Actions
        [AllowAnonymous]
        public ActionResult Submit(Int64? SPID=-1,String SPType=null)
        {
            ServiceProviderRegistrationViewModel viewModel;
            CSS.Models.User loggedInUser = CSS.AuthenticationUtility.GetUser();
            //User Loggin as SP and is non admin
            if (SPType == "SP")
                SPID = loggedInUser.UserId;

            if (SPID == -1)
            {
                //The user is about to register
                viewModel = new ServiceProviderRegistrationViewModel();
            }
            else
            {
                //The user is editing an existing record
                viewModel = new ServiceProviderRegistrationViewModel(SPID.Value);

                //Branch Location should pull the address of Main Locaion
                if (viewModel.user.User1 != null)
                {
                    viewModel.user.StreetAddress = viewModel.user.User1.StreetAddress; 
                }
                //if User login as a Service Provider and who not an admin user
                if (loggedInUser != null && loggedInUser.UserTypeId != 2 && SPType=="SP")
                {
                    viewModel.user.City = "";
                    viewModel.user.State = "";
                    viewModel.user.Zip = "";
                    viewModel.user.UserId = -1;
                    viewModel.user.UserName = "";
                    viewModel.user.Password = "";
                    viewModel.user.MgrId = SPID;
                }
                else
                {
                    viewModel.user.Password = Cypher.DecryptString(Cypher.ReplaceCharcters(viewModel.user.Password));
                }
              
             }
            return View(viewModel);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Submit(FormCollection collection, HttpPostedFileBase profileImage, ServiceProviderRegistrationViewModel viewModel, Int64 ID = -1)
        {
            try
            {
                CSS.Models.User loggedInUser = CSS.AuthenticationUtility.GetUser();
                viewModel.user.UserId = ID;
                if (isFormValid(viewModel, collection, ID))
                {
                    if (ID == -1)
                    {
                        #region Users Table

                        int hdnResiRowCount = Convert.ToInt32(collection["hdnResiRowCount"]);
                        viewModel.user.Password = Cypher.EncryptString(collection["user.Password"].ToString());
                        viewModel.user.BusinessDesc = collection["user.Company1.BusinessDesc"];
                        ObjectParameter outUserid = new ObjectParameter("UserId", DbType.Int32);

                        css.SPRegistrationUsersInsert(outUserid, viewModel.user.UserName, viewModel.user.Password, 1, viewModel.user.FirstName, viewModel.user.MiddleInitial,
                             viewModel.user.LastName, viewModel.user.StreetAddress, viewModel.user.City, viewModel.user.State, viewModel.user.Zip, "",
                             viewModel.user.Email, viewModel.user.Twitter, viewModel.user.Facebook, viewModel.user.SSN, viewModel.user.HomePhone, "",
                             viewModel.user.MobilePhone, "", "", true, viewModel.user.GooglePlus, viewModel.user.AddressLine1, viewModel.user.AddressPO,
                             viewModel.user.NetworkProviderId, viewModel.user.BusinessDesc, viewModel.user.LinkedInAddress, viewModel.user.JobTitle, viewModel.user.HeadCompanyId);


                        viewModel.user.UserId = ID = Convert.ToInt64(outUserid.Value);

                        css.SaveChanges();
                        #endregion

                        #region ServiceProviderDetails Table

                        //string QbVendorid = null;                         
                        //User user = css.Users.Find(viewModel.user.UserId);                   
                        //if(user.MgrId != null && user.MgrId != 0)
                        //{                            
                        //    ServiceProviderDetail spd = css.ServiceProviderDetails.Find(user.MgrId);
                        //    QbVendorid = spd.QBVendorId;
                        //}

                        css.usp_ServiceProviderDetailsNewInsert(Convert.ToInt64(outUserid.Value), viewModel.user.ServiceProviderDetail.IsKnowByOtherNames, viewModel.user.ServiceProviderDetail.KnowByOtherNames, viewModel.user.ServiceProviderDetail.DBA_LLC_Firm_Corp,
                            viewModel.user.ServiceProviderDetail.TaxID, viewModel.user.ServiceProviderDetail.MobileHome, viewModel.user.ServiceProviderDetail.Rank, viewModel.user.ServiceProviderDetail.DriversLicenceNumber,
                            viewModel.user.ServiceProviderDetail.DriversLicenceState, isDatetime(viewModel.user.ServiceProviderDetail.DOB), viewModel.user.ServiceProviderDetail.IsDBA, viewModel.user.ServiceProviderDetail.FederalTaxClassification,
                            viewModel.user.ServiceProviderDetail.LLCTaxClassification, viewModel.user.ServiceProviderDetail.AppraiserLicense, viewModel.user.ServiceProviderDetail.AdjusterLicense, viewModel.user.ServiceProviderDetail.BusinessLicense,
                            viewModel.user.ServiceProviderDetail.CompanyAppraisersCount, viewModel.user.ServiceProviderDetail.AppraiserType, viewModel.user.ServiceProviderDetail.IsProvideTrainingOfAppraisers, viewModel.user.ServiceProviderDetail.HasOfficeReviewCompleted, isFloat(viewModel.user.ServiceProviderDetail.ReviewedPercentage),
                            viewModel.user.ServiceProviderDetail.IsProvideApprHandlingInsts, isFloat(viewModel.user.ServiceProviderDetail.ReInspectionPercentage), isInteger(viewModel.user.ServiceProviderDetail.ATATimeOfAssignment), viewModel.user.ServiceProviderDetail.TechTrainingCerti, isFloat(viewModel.user.ServiceProviderDetail.AudatexEST),
                            isFloat(viewModel.user.ServiceProviderDetail.MitchellEST), isFloat(viewModel.user.ServiceProviderDetail.CCCEST), viewModel.user.ServiceProviderDetail.OtherDesc, isFloat(viewModel.user.ServiceProviderDetail.OtherEST), isInteger(viewModel.user.ServiceProviderDetail.CompanyLast12monthEST), viewModel.user.ServiceProviderDetail.AppraisalManagementDesc);

                        css.SaveChanges();
                        #endregion

                        #region Serviceofferings

                        foreach (var serviceID in viewModel.SelectedServiceTypes ?? new int[0])
                        {
                            css.usp_SPServiceOfferingsInsert(Convert.ToInt64(outUserid.Value), serviceID);
                        }

                        #endregion


                        #region Send Welcome email and notification email to Admin
                        //List<string> to = new List<string>();
                        //to.Add(user.Email);
                        //string mailBody = "Dear " + user.FirstName + " " + user.MiddleInitial + " " + user.LastName + ",";
                        //mailBody += "<br />";
                        //mailBody += "<br />Welcome to IADA Claim Solutions Inc. Your account has now been created.";
                        //mailBody += "<br />";
                        //mailBody += "<br />You can now login to your account using the following credentials.";
                        //mailBody += "<br />";
                        //mailBody += "<br />Website Address: " + ConfigurationManager.AppSettings["WebAppURL"].ToString();
                        //mailBody += "<br />User Name: " + user.UserName;
                        //mailBody += "<br />Password: " + user.Password;
                        //mailBody += "<br />";
                        //mailBody += "<br />";
                        //mailBody += "<br />";
                        //mailBody += "<br />";
                        //mailBody += "<br />Thanking you,";
                        //mailBody += "<br />";
                        //mailBody += "<br />Support,";
                        //mailBody += "<br />IADA Claim Solutions Inc.";
                        //Utility.sendEmail(to, MvcApplication.AdminMail, "Welcome to IADA Claim Solutions Inc.", mailBody);

                        //Admin Notification
                        var adminEmailList = css.Users.Where(x => x.UserTypeId == 2).Select(y => y.Email).ToList();
                        if (adminEmailList.Count > 0)
                        {
                            List<string> toEmails = new List<string>();
                            foreach (var email in adminEmailList)
                            {
                                if (!string.IsNullOrEmpty(email))
                                {
                                    toEmails.Add(email);
                                }
                            }
                            if (toEmails.Count > 0)
                            {
                         string mailBody = "<br />";

CSS/Views/ServiceProviderRegistration/CertificationDocsUpload.cshtml
@using System.Configuration
@using CSS
@model BLL.ViewModels.CertificationDocsUploadViewModel
@{
    Layout = null;
    ViewBag.Title = "Company Certification Documents Upload";
    string containerName = ConfigurationManager.AppSettings["SPDocsContainerName"].ToString();
    <style type="text/css">
        body {
            font-family: Verdana;
            font-size: 11px !important;
            color: #727272;
            margin: 0px;
        }
    </style>
}
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        function isFileValid() {
            var isValid = true;
            var file = document.getElementById('certificationFile');
            //var hash = {
            //    '.pdf': 1,
            //    '.PDF': 1
            //};
            //if (check_extension(file.value, hash) != true) {
            //    alert('Select a PDF file.');
            //    isValid = false;
            //}
            if (file.value.trim().length == 0) {
                alert("Select a file");
                isValid = false;
            }
            return isValid;
        }
        function getExtension(filename) {
            var re = /\..+$/;
            var ext = filename.match(re);
            return ext;
        }
        function check_extension(filename, hash) {

            var ext = getExtension(filename);

            if (hash[ext]) {
                return true;
            } else {
                return false;
            }
        }
    </script>
</head>
<body>
    <table>
        <tr>
            <td>@using (Html.BeginForm("CertificationDocsUpload", "ServiceProviderRegistration", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                <table>
                     <tr>
                        <td class="defaultPageText" colspan="2">If the list below does not contain your company certification, kindly save this registration form before proceeding.
                        </td>
                    </tr>
                    <tr>
                        <td class="defaultPageText" width="200" nowrap="nowrap">Select Company Certification:@Html.HiddenFor(model => model.UserId)</td>
                        <td>@Html.DropDownListFor(model => model.SPCId, Model.CertificationList, new { onchange = "this.form.submit();" })
                        </td>
                    </tr>
                    @{
                    if (Model.Certification != null)
                    {
                        bool showUpload = true;
                        if (Model.Certification.IsDocUploaded.HasValue)
                        {
                            if (Model.Certification.IsDocUploaded.Value)
                            {
                                showUpload = false;
                            }
                        }

                        if (showUpload)
                        {
                        <tr>
                            <td class="defaultPageText">Choose File:</td>
                            <td class="defaultPageText">
                                <input type="file" id="certificationFile" name="certificationFile" />
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td align="right">

                                <input type="submit" value="Upload" class="buttonYellow_100" onclick="javascript: return isFileValid();" /></td>
                        </tr>
                        }

                    }
                    }
                </table>
                }
            </td>
        </tr>
        @{
            if (Model.Certification != null)
            {
                if (Model.Certification.IsDocUploaded.HasValue)
                {
                    if (Model.Certification.IsDocUploaded.Value)
                    {
                        string absoluteFileName = Model.Certification.UserId + "/" + System.Configuration.ConfigurationManager.AppSettings["ServiceProviderCertificationDocsFolderName"].ToString() + "/" + Model.Certification.DocFileName;
                        string fileUrl = CloudStorageUtility.GetAbsoluteFileURL(containerName,absoluteFileName);
            <tr>
                <td class="defaultPageText"><a style="padding-right:5px;" href="@fileUrl" target="_blank">
                    <img src="@Url.Content("~/Content/Images/Download.png")" title="Download" width="12" height="12" style="border:none;vertical-align:bottom;"/></a>
                    <a style="padding-right:5px;" href="@Url.Action("CertificationDocsDelete", "ServiceProviderRegistration", new { SPCId = Model.Certification.SPCId })" style="border: none; color: black; cursor: pointer;float:right;">
                        <img src="@Url.Content("~/Content/Images/Cancel.png")" title="Remove" alt="Remove" width="12" height="12" style="border:none;vertical-align:bottom;" onclick = "return confirm('Are you sure you want to Delete ?')" /></a> @Model.Certification.Certification</td>
                <td class="defaultPageText"></td>
            </tr>
                    }
                }
            }
        }
    </table>

</body>

CSS/Views/ServiceProviderRegistration/EmailMarketingSPRegistration.cshtml
@{
    ViewBag.Title = "UpdateSuccess";
}
<script src="@Url.Content("~/Scripts/DateTimePicker/jquery-1.8.0.min.js")" type="text/javascript"></script>
<h2>Update Successful</h2>
Your details have successfully been updated
<script type="text/javascript">
    $(function () {
        var width = '900';
        var height = '600';
        
        var windowFeatures = "dialogWidth:" + width + ";dialogHeight:" + height + ",status=0,resizable=1,title=no,location=no,scrollbars=1,menubar=no,addressbar='no',left=" + "100" + ",top=" + "100"+ "screenX=" + 100 + ",screenY=" + 100;
        window.showModalDialog("@System.Configuration.ConfigurationManager.AppSettings["EmailMarketingSPRegistration"]", 'EmailREgistration', windowFeatures);
    });
    </script>
   

CSS/Views/ServiceProviderRegistration/LicenseDocsUpload.cshtml
@using System.Configuration
@using CSS
@model BLL.ViewModels.LicenseDocsUploadViewModel
@{
    Layout = null;
    ViewBag.Title = " License Documents Upload";
    string containerName = ConfigurationManager.AppSettings["SPDocsContainerName"].ToString();
    <style type="text/css">
        body {
            font-family: Verdana;
            font-size: 11px !important;
            color: #727272;
            margin: 0px;
        }
    </style>
}
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
     <script type="text/javascript">
         function isFileValid() {
             var isValid = true;
             var file = document.getElementById('licenseFile');
             //var hash = {
             //    '.pdf': 1,
             //    '.PDF': 1
             //};
             //if (check_extension(file.value, hash) != true) {
             //    alert('Select a PDF file.');
             //    isValid = false;
             //}
             if (file.value.trim().length == 0) {
                 alert("Select a file");
                 isValid = false;
             }
             return isValid;
         }
         function getExtension(filename) {
             var re = /\..+$/;
             var ext = filename.match(re);
             return ext;
         }
         function check_extension(filename, hash) {

             var ext = getExtension(filename);

             if (hash[ext]) {
                 return true;
             } else {
                 return false;
             }
         }
    </script>
</head>
<body>
    <table>
        <tr>
            <td>@using (Html.BeginForm("LicenseDocsUpload", "ServiceProviderRegistration", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                <table>
                     <tr>
                        <td class="defaultPageText" colspan="2">If the list below does not contain your license, kindly save this registration form before proceeding.
                        </td>
                    </tr>
                    <tr>
                        <td class="defaultPageText" width="200" nowrap="nowrap">Select License:@Html.HiddenFor(model => model.UserId)</td>
                        <td>@Html.DropDownListFor(model => model.SPLId, Model.LicenseList, new { onchange = "this.form.submit();" })
                        </td>
                    </tr>
                    @{
                    if (Model.License != null)
                    {
                        bool showUpload = true;
                        if (Model.License.IsDocUploaded.HasValue)
                        {
                            if (Model.License.IsDocUploaded.Value)
                            {
                                showUpload = false;
                            }
                        }

                        if (showUpload)
                        {
                        <tr>
                            <td class="defaultPageText">Choose File:</td>
                            <td class="defaultPageText">
                                <input type="file" id="licenseFile" name="licenseFile" />
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td align="right">

                                <input type="submit" value="Upload" class="buttonYellow_100" onclick="javascript: return isFileValid();" /></td>
                        </tr>
                        }

                    }
                    }
                </table>
                }
            </td>
        </tr>
        @{
            if (Model.License != null)
            {
                if (Model.License.IsDocUploaded.HasValue)
                {
                    if (Model.License.IsDocUploaded.Value)
                    {
                        string absoluteFileName = Model.License.UserId + "/" + ConfigurationManager.AppSettings["ServiceProviderLicenseDocsFolderName"].ToString() + "/" + Model.License.FileName;
                        string fileUrl = CloudStorageUtility.GetAbsoluteFileURL(containerName,absoluteFileName);
            <tr>
                <td class="defaultPageText"><a style="padding-right:5px;" href="@fileUrl" target="_blank">
                    <img src="@Url.Content("~/Content/Images/Download.png")" title="Download" width="12" height="12" style="border:none;vertical-align:bottom;"/></a>
                    <a style="padding-right:5px;" href="@Url.Action("LicenseDocsDelete", "ServiceProviderRegistration", new { SPLId = Model.License.SPLId })" style="border: none; color: black; cursor: pointer;float:right;">
                        <img src="@Url.Content("~/Content/Images/Cancel.png")" title="Remove" alt="Remove" width="12" height="12" style="border:none;vertical-align:bottom;" onclick = "return confirm('Are you sure you want to Delete ?')" /></a> @Model.License.LicenseNumber - @Model.License.Type</td>
                <td class="defaultPageText"></td>
            </tr>
                    }
                }
            }
        }
    </table>

</body>

CSS/Views/ServiceProviderRegistration/List.cshtml
@model IEnumerable<BLL.ClaimTypesGetListNew_Result>

<h2>List</h2>
No of Years

<table>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
               
                @Html.TextBoxFor(modelItem => item.YearsOfExperience,new { style = "width:300px" })

            </td>
            @* <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>*@
        </tr>
    }
    <tr>
        <td>
            <input id="btnSubmit" type="button" />
        </td>

    </tr>
</table>

CSS/Views/ServiceProviderRegistration/ProcessESigningDoc.cshtml
@model BLL.ViewModels.ProcessESigningDocViewModel
@{
    Layout = "~/Views/Shared/_BlankLayout.cshtml";
    ViewBag.Title = "ProcessESigningDocument";
}

<script type="text/javascript">
    $(function () {
        $("#close").click(function () { window.close(); });
    });
</script>
<table width="100%">
    <tr>
        <td class="mainHeader">@Model.DocTitle </td>
    </tr>
    <tr>
        <td class="content">
            <iframe src="@Model.DocURL" frameborder="0" width="100%" height="480"></iframe>

        </td>
    </tr>
    <tr>
        <td class="footer" style="text-align:center;">
            <input type="button" value="Exit" id="close" style="width:100px" />
            <br />
        </td>
    </tr>
</table>

CSS/Views/ServiceProviderRegistration/Submit.cshtml
@model BLL.ViewModels.ServiceProviderRegistrationViewModel


@*<style type="text/css">
    .waiting-box {
        display: block;
        position: fixed; /* fixed position so it doesn't scroll */
        _position: fixed; /* hack for internet explorer 6*/
        z-index: 99; /* on top of everything else */
        top: 0;
        left: 0;
        /*left: 50%;
        top: 50%;*/ /* displayed on the top of the page, just like Gmail's yellow info-box */
        /*background: white;*/
        background-color: black;
        border-radius: 4px;
        /*margin-top: -147px;*/
        opacity: 0.8;
        filter: alpha(opacity=80);
        -moz-opacity: 0.8;
        min-height: 100%;
        width: 100%;
    }


    .loading {
        font-family: Arial;
        font-size: 10pt;
        /*border: 5px solid #67CFF5;*/
        width: 150px;
        height: 150px;
        display: none;
        position: fixed;
        background-color: White;
        z-index: 999;
    }
</style>*@
<div class="loading" align="center">
    <img src="@Url.Content("~/Content/Images/spinner.gif")" width="150" height="150" />
</div>
 @Html.Partial("_IADAServiceProviderBasicInfo", Model)
<div id="ErrorPopup" class="modal fade in" tabindex="-1" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modalHead">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Errors</h4>
            </div>
            <div class="modal-body">
                <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto;">
                    <div class="scroller" style="overflow: hidden; width: auto;" data-always-visible="1" data-rail-visible1="1" data-initialized="1">
                        <div class="form-body">
                            <div id="Errorlog" style="color: red;">
                               @Html.ValidationSummary()
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" ng-click="searchSPMapclick()" class="btn dark btn-outline">Ok</button>
            </div>
        </div>
    </div>
</div>

@section PageLevelScript{

    <script src="~/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js"></script>
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>
    <script type="text/javascript">
        var populateZipUrl = '@Url.Content("~/Utility/GetZipCodeInfo")';
        var HeadCompanyDetailsUrl = '@Url.Content("~/ServiceProviderRegistration/GetHeadCompanyDetails")';
        var InternalContactRejectUrl = '@Url.Action("RejectInternalContact", "ServiceProviderRegistration")';
        var SaveInternalContact = '@Url.Action("SaveInternalContact", "ServiceProviderRegistration")';
        var CreateInternalContactPopup = '@Url.Content("~/ServiceProviderRegistration/EditInternalContact")';
        var InternalContactList = '@Url.Content("~/ServiceProviderRegistration/GetInternalContactList")';
        var federal = $.trim('@Model.user.ServiceProviderDetail.FederalTaxClassification');
        var ISDBA = '@Model.user.ServiceProviderDetail.IsDBA';
    </script>
     <script src="~/Scripts/Customs/SPRegistration.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            @if(!Html.ViewData.ModelState.IsValid)
            {
                @:$("#ErrorPopup").modal("show");
            }
            debugger;
            var EnableLLC = '@(ViewBag.EnableLLC)';

            $('#txtPassword').val('@Model.user.Password');
            $('#txtConfPassword').val('@Model.user.Password');

            if (EnableLLC == '1') {
                $('#tddbaradio input[type="radio"]').removeAttr("disabled");
                $('#ddlFederalTaxClassification').removeAttr("disabled");
                $('#ddlLLCTaxClassification').removeAttr("disabled");
                $('#hdnmodifyllc').val("1");

            }
            else {
                $('#hdnmodifyllc').val("0");
            }
           
       });

    </script>
}

CSS/Views/ServiceProviderRegistration/SubmitSuccess.cshtml
@{
    ViewBag.Title = "SubmitSuccess";
}

<h2>Registration Successful</h2>

You may now login to your account to upload your documents or update other registration details.

CSS/Views/ServiceProviderRegistration/UpdateSuccess.cshtml
@{
    ViewBag.Title = "UpdateSuccess";
}

<h2>Update Successful</h2>
Your details have successfully been updated